language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t killuminati3001/react-test -f ./client/Dockerfile.dev ./client 
script:
    - docker run -e CI=true killuminati3001/react-test npm run test

after_success:
    - docker build -t killuminati3001/multi-client ./client
    - docker build -t killuminati3001/multi-nginx ./nginx
    - docker build -t killuminati3001/multi-server ./server
    - docker build -t killuminati3001/multi-worker ./worker
    # Log into Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push images
    - docker push killuminati3001/multi-client
    - docker push killuminati3001/multi-server
    - docker push killuminati3001/multi-worker
    - docker push killuminati3001/multi-nginx
      
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-912220572989"
    bucket_path: "docker-multi"
    access_key_id: $AWS_SECRET_KEY
    secret_access_key: $AWS_SECRET_SCT
    on:
        branch: master

